linux-mbmicro_4.0.1: Remove PKG:{PN} which rename to existing package
ERROR: linux-mbmicro-4.0.1-r0 do_package: package "kernel-base" is renamed to "kernel-base" using PKG:kernel-base, but package name already exists