linux-mbmicrov2_4.10.12: Remove PKG:{PN} which rename to existing package
ERROR: linux-mbmicrov2-4.10.12-r0oea4.1-r3 do_package: package "kernel-base" is
renamed to "kernel-base" using PKG:kernel-base, but package name already exists

https://git.openembedded.org/openembedded-core/commit/?id=f6cb63d3a871c4eef52d981131a56bf41aa1dcdf